# Generated by Django 3.1.6 on 2021-02-25 09:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_no',
            field=models.PositiveBigIntegerField(default=accounts.models.random_int, unique=True),
        ),
    ]
